name: Build bottles


on:
  push:
    tags:
      - 'v*.*.*'  # Ejecuta cuando se crea un tag que sigue el patrón semver (v1.0.0, v2.1.3, etc.)
jobs:
  bottle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@v2
      - run: brew install gcc make
      - run: brew test-bot --ci-upload Formula/toolchain.rb